### PR TITLE
Add valid hours prop

### PR DESCRIPTION
**Pull request by vencho-mdp**
Solves [#970](https://github.com/nathanreyes/v-calendar/issues/970).

### CODE REVIEW

**Comment by shakhzodkudratov** [comment]
hey, can you give some documentation about changes you made? thank you very much for this feature!

**Comment by vencho-mdp** [comment]
Hi! So I added a prop called validHours, which is an object, so the developer can restrict the range of possible hours the user can select. I'd this problem two days ago, and I thought that maybe somebody else might have had it.

**Comment by vencho-mdp** [comment]
Would you like me to add this feature to the docs?

**Comment by vencho-mdp** [comment]
Hi! Would you like to merge this, I really need this feature.

**Comment by vencho-mdp** [comment]
Any updates?

**Comment by TLA020** [comment]
Is this going to be released any time soon?

**Comment by nathanreyes** [comment]
`v2.4.0` or `v3.0.0-alpha.7` is available with a new [`valid-hours`](https://vcalendar.io/datepicker.html#valid-hours) prop. You can use an array, object or function to limit the hours available.

**Comment by TLA020** [comment]
Thanks will try!

**Pull request merged**
