### PR TITLE
updated lodash to fix security vulnerability

### PR DESCRIPTION
**Pull request by contractorwolf**
We found that the version of lodash has security vulnerabilities and this just updates it to the latest (4.17.20)

### CODE REVIEW

**Comment by nathanreyes** [comment]
No quibbles with updating Lodash...however, this package uses yarn so just needs `package-lock.json` => `yarn.lock`.

**Comment by contractorwolf** [comment]
undid the previous commit to make sure I didnt have the package-lock.json and redid it in yarn, let me know if that works

**Comment by mattsGitHub123** [comment]
@nathanreyes Anyway you could include this in an upcoming release? my team is also waiting on this update

**Review by nathanreyes — APPROVED** [review]
Looks good to me. 👍

**Pull request merged**
