### PR TITLE
Show iso week numbers on the left side of the calendar

### PR DESCRIPTION
**Pull request by lokedahlstrom**
Introduces a new property, `show-weeknumbers`, which if set shows week numbers on the left side of the calendar.

With the property set `<v-calendar show-weeknumbers />` we get something like what is shown in the picture below:
Skärmavbild 2021-02-13 kl  21 25 20

Styling for the numbers is controlled by the class `.vc-weeknumber-content`.

A live demo is available [here](https://deploy-preview-790--vcalendar.netlify.app/), scroll down to "Week numbers".

### CODE REVIEW

**Comment by lokedahlstrom** [comment]
Any input on this @nathanreyes ?

**Comment by nathanreyes** [comment]
@lokedahlstrom This looks great...I've been meaning to get to properly reviewing it since it is a much requested feature. 
It has been a crazy last week here in Texas with our weather but I'll look into getting this into the next minor release.

**Comment by nathanreyes** [comment]
I'm releasing a patch version today for some longer standing bugs, but this will go in the next minor release.

Thanks for your contribution.

**Comment by lokedahlstrom** [comment]
cool, looking forward to the release! Big thanks for accepting the PR, and for a great component!

**Pull request merged**
