### PR TITLE
chore: bump Vue CLI & dependencies

### PR DESCRIPTION
**Pull request by DavidRouyer**
Updated Vue CLI version to 4.4.4

### CODE REVIEW

**Comment by nathanreyes** [comment]
@DavidRouyer plan to take a look at this today or tomorrow

**Comment by DavidRouyer** [comment]
@nathanreyes Once this is merged I'll work on reducing the file size of the library

**Comment by nathanreyes** [comment]
@DavidRouyer Can you educate me on `core-js` and its use? Does it not need to be explicitly imported where needed?

**Comment by DavidRouyer** [comment]
@nathanreyes core-js is the polyfill engine used by Babel to select the list of polyfills needed for the targeted browsers. For more information you can take a look at : https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md and https://babeljs.io/blog/2019/03/19/7.4.0#core-js-3-7646-https-githubcom-babel-babel-pull-7646.

When I create a new project with the Vue-CLI, core-js is added as a dependency this is why I added it!

**Comment by DavidRouyer** [comment]
@nathanreyes Is it okay for you?

**Pull request merged**
